# Generated by Django 4.2.4 on 2023-08-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_state_customer_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tc_no',
            field=models.IntegerField(default=12345678911),
            preserve_default=False,
        ),
    ]
