# Generated by Django 4.2.4 on 2023-08-29 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_tc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tc_no',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('^[1-9]{1}[0-9]{9}[02468]{1}$', code='invalid_number', message='Invalid Tc No ')]),
        ),
    ]
